apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: streamlit
  name: streamlit
spec:
  ports:
  - name: "8501"
    nodePort: 31348
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: streamlit
  type: NodePort
status:
  loadBalancer: {}
