name: MLOPS CI Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ] 
  
jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.13'
          
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Install requirements
        run: |
          pip install -r requirements.txt 